name = "qq-auth"
main = "worker-upload.js"
compatibility_date = "2024-01-01"

[[kv_namespaces]]
binding = "BLUEPRINT_KV"
id = "216caeb9e0a84e4cbf59287d08fbcf9e"

[[r2_buckets]]
binding = "BLUEPRINT_R2"
bucket_name = "blueprint-files"